### PR TITLE
Completed beta version.

### PR DESCRIPTION
**Pull request by lpsandaruwan**
Okay. hope you will enjoy this. :-)

### CODE REVIEW

**Comment by pathumego** [comment]
Ill chek now :)

**Comment by madhubhasha** [comment]
getting this error 

mooniak@mooniak:~$ sh '/home/mooniak/Downloads/animager-master/src/install.sh' 
cp: cannot stat ‘profiles/*.prof’: No such file or directory
[sudo] password for mooniak: 
cp: cannot stat ‘*.py’: No such file or directory
/home/mooniak/Downloads/animager-master/src/install.sh: 17: /home/mooniak/Downloads/animager-master/src/install.sh: g++: not found
cp: omitting directory ‘animager’
mooniak@mooniak:~$

**Comment by pathumego** [comment]
machan can you give me a quick step by step

**Comment by lpsandaruwan** [comment]
@madhubhasha - What is your operating system ? mac ?
@pathumego - sure !!!

**Comment by madhubhasha** [comment]
elementry freya

**Comment by pathumego** [comment]
@lpsandaruwan  will this work on mac ? i guess we need imagemagik

**Comment by lpsandaruwan** [comment]
@madhubhasha  - 
I recommend you to do the installation manually, I will come up with a solution soon. Follow these steps.

You need to install the C++ compiler. To install it,
sudo apt-get install g++

To clean the previous buggy installation,
sudo rm -r /opt/animager /usr/bin/animager
rm -r ~/animager

cd into the src folder and,
mkdir -p ~/animager ~/animager/morph-cache ~/animager/profiles
cp -r profiles/*.prof ~/animager/profiles/
sudo mkdir -p /opt/animager
g++ cmd.cpp -o animager
sudo cp -r *.py /opt/animager/
sudo cp animager /usr/bin/

**Comment by lpsandaruwan** [comment]
@pathumego I need to find a mac to test. :-)

**Comment by madhubhasha** [comment]
ok so now what do i do to get this going? i have a inkscape svg file

**Comment by pathumego** [comment]
@lpsandaruwan I got a mac :) lets test sometime this week :)

**Comment by lpsandaruwan** [comment]
@pathumego - great :+1:

**Comment by lpsandaruwan** [comment]
@madhubhasha - 
you can do this,
animager -p hd-720p -i [path-to-your-image] -o [path-to-your-output-folder]
and you can get a video, of your working progress. What animager does is rolling among the git commits, generate temporary images and make a video using thos temporary images. :-)

**Pull request merged**
